-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
    FROM REST_INFO AS RI
    
    JOIN 
        (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAV
            FROM REST_INFO
            GROUP BY FOOD_TYPE
        ) AS JRI ON RI.FOOD_TYPE = JRI.FOOD_TYPE AND RI.FAVORITES = JRI.FAV
    
    ORDER BY RI.FOOD_TYPE DESC