-- 코드를 입력하세요
# SELECT
#     # DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%Y') AS YEAR,
#     # DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%m') AS MONTH, 
#     YEAR(ONLINE_SALE.SALES_DATE) AS YEAR,
#     MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
#     COUNT(ONLINE_SALE.USER_ID) AS PUCHASED_USERS,
#     # (COUNT(ONLINE_SALE.USER_ID) / COUNT(DATE_FORMAT(USER_INFO.JOINED, '%Y') = 2021)) AS PUCHASED_RATIO
#     ROUND((COUNT(DISTINCT ONLINE_SALE.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021')),1) AS PUCHASED_RATIO
#     FROM ONLINE_SALE
#     LEFT OUTER JOIN USER_INFO ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
#     WHERE  YEAR(USER_INFO.JOINED)=2021 AND YEAR(ONLINE_SALE.SALES_DATE) IS NOT NULL
#     # GROUP BY DATE_FORMAT(ONLINE_SALE.SALES_DATE, '%Y%m')
#     GROUP BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE)
#     ORDER BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE)
    
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, (COUNT(DISTINCT O.USER_ID)) AS PURCHASED_USER, ROUND((COUNT(DISTINCT O.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO
WHERE YEAR(JOINED) = "2021") , 1) AS PUCHASED_RATIO  FROM ONLINE_SALE O
JOIN USER_INFO U
ON O.USER_ID = U.USER_ID
WHERE YEAR(U.JOINED) = "2021"
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)