-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",
           CONCAT(B.BOARD_ID,CONCAT('/',CONCAT(F.FILE_ID,CONCAT(F.FILE_NAME,FILE_EXT)))))
           AS FILE_PATH
    FROM (SELECT BOARD_ID, VIEWS FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) AS B
    INNER JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
    ORDER BY FILE_PATH DESC