-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME,
    SUM(B.PRICE) AS TOTAL_SALES
    FROM (SELECT * FROM USED_GOODS_BOARD WHERE USED_GOODS_BOARD.STATUS = 'DONE') B
    INNER JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
    GROUP BY B.WRITER_ID
    HAVING SUM(B.PRICE) >= 700000
    ORDER BY TOTAL_SALES