-- 코드를 입력하세요
SELECT B.CATEGORY, B.PRICE, B.PRODUCT_NAME
    FROM FOOD_PRODUCT AS B
    JOIN (
        SELECT CATEGORY, MAX(PRICE) AS MP
            FROM FOOD_PRODUCT
            GROUP BY CATEGORY
        ) AS JB ON B.CATEGORY = JB.CATEGORY AND B.PRICE = JB.MP
    HAVING B.CATEGORY = '김치'
    OR B.CATEGORY = '과자'
    OR B.CATEGORY = '국'
    OR B.CATEGORY = '식용유'
    ORDER BY B.PRICE DESC