-- 코드를 입력하세요
SELECT CH.HISTORY_ID,
    ROUND(((DATEDIFF(END_DATE,START_DATE)+1)* CC.DAILY_FEE)*(
        CASE WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN 0.85
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30
                AND DATEDIFF(END_DATE,START_DATE)+1 < 90 THEN 0.92
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7
                AND DATEDIFF(END_DATE,START_DATE)+1 < 30 THEN 0.95
            ELSE 1
            END),0)
            AS FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
    JOIN CAR_RENTAL_COMPANY_CAR AS CC
        ON CC.CAR_ID = CH.CAR_ID
    WHERE CC.CAR_TYPE = '트럭'
    ORDER BY FEE DESC, CH.HISTORY_ID DESC
    
# SELECT CAR_TYPE,100 - REGEXP_REPLACE(DISCOUNT_RATE,'%',"")
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 