-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
    FROM APPOINTMENT AS A
    JOIN PATIENT AS P ON P.PT_NO = A.PT_NO
    JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
    WHERE A.APNT_CNCL_YMD IS NULL
        AND DATE(A.APNT_YMD) = "2022-04-13"
        AND A.MCDP_CD = 'CS'
    ORDER BY A.APNT_YMD