-- 코드를 입력하세요
SELECT RH.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE MONTH(START_DATE) = 10
    ) AS RH
    ON C.CAR_ID = RH.CAR_ID
    WHERE C.CAR_TYPE = '세단'
    GROUP BY RH.CAR_ID 
    ORDER BY RH.CAR_ID DESC